			$(document).ready(function(){
				$(".boxes").hover(
					function(){
						$(this).addClass("banana");
					},
					function(){
						$(this).removeClass("banana");	
					}
				);
				$(".boxes").click(function(){
					alert($(this).text());
				});
			});